Import atheme-1.1.0

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -5,10 +5,11 @@
 #
 # This file is a simple setup script.
 #
-# $Id: setup 2883 2005-10-14 21:50:46Z nenolod $
+# $Id: setup 5253 2006-05-05 01:52:28Z nenolod $
 
 PREFIX="$HOME/atheme"
 LARGENET="no"
+SASL="yes"
 VERSION=`grep AC_INIT configure.ac | awk '{print \$2}' | sed s:\,::g`
 
 export ok INPUT
@@ -92,7 +93,60 @@ case "$LARGENET" in
     ;;
 esac
 
+echo ""
+
+ok=0
+echo "Would you like to enable SASL authentication? This is a fairly"
+echo "new feature; most IRCDs do not support it yet, however charybdis"
+echo "does. Other IRCds may follow soon."
+while [ $ok -eq 0 ] ; do
+  echo -n "[$SASL] "
+  if read INPUT ; then : ; else echo "" ; exit 1 ; fi
+  if [ ! "$INPUT" ] ; then
+    INPUT=$SASL
+    ok=1
+  else
+    ok=1
+  fi
+done
+SASL=$INPUT
+
+case "$SASL" in
+  [Yy])
+    ARGS="$ARGS --enable-sasl"
+    ;;
+  Yes)
+    ARGS="$ARGS --enable-sasl"
+    ;;
+  yes)
+    ARGS="$ARGS --enable-sasl"
+    ;;
+esac
+
+echo ""
+
+ok=0
+echo "Would you like to pass any additional options to configure? If so,"
+echo "place them here:"
+while [ $ok -eq 0 ] ; do
+  echo -n "[no] "
+  if read INPUT ; then : ; else echo "" ; exit 1 ; fi
+  if [ ! "$INPUT" ] ; then
+    INPUT=""
+    ok=1
+  else
+    ok=1
+  fi
+done
+ARGS="$ARGS $INPUT"
+
 sh configure $ARGS
+if [ $? != 0 ]; then
+	echo "Configure failed"
+	echo "Command was: sh configure $ARGS"
+	echo "Please fix this and try again"
+	exit 1
+fi
 
 echo ""
 echo "Press enter to begin compilation."
@@ -100,6 +154,12 @@ echo -n ""
 if read INPUT ; then : ; else echo "" ; exit 1 ; fi
 
 make
+if [ $? != 0 ]; then
+	echo "Compilation failed"
+	echo "Command was: make"
+	echo "Please fix this and try again"
+	exit 1
+fi
 
 echo ""
 echo "Press enter to begin installation."
@@ -107,6 +167,12 @@ echo -n ""
 if read INPUT ; then : ; else echo "" ; exit 1 ; fi
 
 make install
+if [ $? != 0 ]; then
+	echo "Installation failed"
+	echo "Command was: make install"
+	echo "Please fix this and try again"
+	exit 1
+fi
 
 echo "----------------------------------------------------------------"
 echo ">>> Atheme setup completed on `date`"
